In [ ]:
1.   What is a Support Vector Machine (SVM), and how does it work?
   -> A Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks.

  #  1. Separating Hyperplane:
     *  SVMs aim to find a decision boundary (hyperplane) that effectively divides data points into different classes.
     *  In a 2D space, this hyperplane is a line. In higher dimensions, it becomes a plane or a hyperplane.

# 2. Support Vectors:
    *  Support vectors are the data points closest to the separating hyperplane.
    *  They are crucial in defining the margin and the position of the hyperplane.
    *  SVMs are less sensitive to other data points that are further away from the margin.

# 3. Kernel Trick:
     *  SVMs can handle non-linearly separable data by using a kernel function.
     *  The kernel function transforms the data into a higher-dimensional space where it might be linearly separable.

# 4. Classification and Regression:
# Classification:
     SVMs classify data points into different categories based on their position relative to the hyperplane.

# 5. Key Advantages of SVMs:
# Effective in high-dimensional spaces:
           They can handle a large number of features effectively.
# Memory efficient:
           They rely on support vectors, which can make them memory efficient for large datasets.
# Versatile:
 They can be used for both classification and regression tasks

In [ ]:
2.  Explain the difference between Hard Margin and Soft Margin SVM.
    #  -> * Hard Margin SVM

# Requires Linearly Separable Data:
             This method is only applicable when all data points can be perfectly separated by a hyperplane with no overlaps or outliers.
# No Misclassifications:
             The primary goal is to find a hyperplane that provides the widest possible margin between the classes without any data
               points being misclassified or falling within the margin.
# Sensitive to Outliers:
         Because it demands perfect separation, a single outlier can significantly influence the decision boundary, leading to a poorly generalized model.
# Soft Margin SVm

# Accommodates Imperfect Data:
                This approach is designed for datasets that are not perfectly linearly separable, including those with noise
                or overlapping classes.
# Uses Slack Variables:
              To allow for flexibility, soft margin SVM introduces "slack variables" (ξi) that permit some data points to be within
              the margin or even on the wrong side of the hyperplane.
# Balances Margin and Error:
              The model optimizes by finding a hyperplane that balances maximizing the margin with minimizing the penalties for misclassified
               points, using a regularization parameter (often denoted as C) to control this trade-off.
# More Robust and Generalizable:
               By tolerating a small error on the training data, soft margin SVM is less sensitive to outliers and tends to

In [ ]:
3. : What is the Kernel Trick in SVM? Give one example of a kernel and explain its use case.
     -> The Kernel Trick in Support Vector Machines (SVMs) is a technique that allows SVMs to find a linear decision boundary in
        a higher-dimensional feature space without explicitly transforming the data into that higher dimension. This is particularly
        useful when the data is not linearly separable in its original feature space.



# Example of a Kernel:
 Radial Basis Function (RBF) Kernel
     The Radial Basis Function (RBF) kernel, also known as the Gaussian kernel, is a widely used kernel in SVMs. Its formula is given by:

K(x, y) = exp(-γ * ||x - y||²)

where:

x and y are the input data points.
||x - y||² is the squared Euclidean distance between x and y.
γ (gamma) is a hyperparameter that controls the influence of individual training samples.


In [ ]:
4. : What is a Naïve Bayes Classifier, and why is it called “naïve”?
    -> A Naïve Bayes classifier is a simple, probabilistic machine learning algorithm that uses Bayes' theorem to predict class
       membership probabilities for data points.

      #  Naïve Bayes Classifier Does
# Probabilistic Classification:
      It calculates the probability of a given data point belonging to different classes.
# Bayes' Theorem:
            It's built upon Bayes' theorem, which provides a way to update prior beliefs (prior probability) based on new evidence
              to arrive at a revised belief (posterior probability).

# Why It's Called "Naïve"

# Unrealistic Independence Assumption:
        The "naïve" label comes from the algorithm's fundamental assumption that its features are independent.
# Real-World Data is Complex:
         In reality, features in most datasets are not truly independent; they often have correlations and dependencies that this algorithm ignores.
# Surprising Effectiveness:
           Despite being "naïve," the algorithm often performs surprisingly well in practice, particularly in tasks like text classification,
             spam filtering, and sentiment analysis. This is because the independence assumption often simplifies calculations without
             significantly compromising the overall accuracy for certain types of problems

In [ ]:
5. : Describe the Gaussian, Multinomial, and Bernoulli Naïve Bayes variants. When would you use each one?
   ->  Gaussian Naive Bayes assumes features follow a normal distribution and is used for continuous data. Multinomial Naive
      Bayes works with discrete data, like word counts in text, and is often used in Natural Language Processing tasks.
     Bernoulli Naive Bayes is designed for binary or boolean features, such as whether a word appears in a document or not.
  #  Gaussian Naive Bayes:
Assumption:
      Features are continuous and follow a normal (Gaussian) distribution.
# Use Cases:
       Suitable for datasets with continuous numerical features, like height, weight, temperature, or any measurement where data points tend to cluster around a mean.
Exa/mple:
        Classifying flower species based on petal length and width, where petal measurements are likely to be normally distributed.

# Assumption:
         Features are discrete and represent counts or frequencies.
Use Cases:
           Commonly used in text classification, spam filtering, and document categorization, where word counts or term frequencies are important

In [1]:
6.  : Write a Python program to:
● Load the Iris dataset
● Train an SVM Classifier with a linear kernel
● Print the model's accuracy and support vectors.



from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train an SVM Classifier with a linear kernel
# C is the regularization parameter. A smaller C means more regularization.
svm_model = SVC(kernel='linear', C=1.0)
svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Print the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Print the support vectors
# Support vectors are the data points closest to the hyperplane
print("\nSupport Vectors:")
# The support_vectors_ attribute contains the coordinates of the support vectors
print(svm_model.support_vectors_)

# Print the indices of the support vectors in the training data
print("\nIndices of Support Vectors in training data:")
print(svm_model.support_)


Model Accuracy: 1.0000

Support Vectors:
[[4.8 3.4 1.9 0.2]
 [5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [5.6 3.  4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.  2.7 5.1 1.6]
 [6.3 2.5 4.9 1.5]
 [6.1 2.9 4.7 1.4]
 [6.5 2.8 4.6 1.5]
 [6.9 3.1 4.9 1.5]
 [6.3 2.3 4.4 1.3]
 [6.3 2.8 5.1 1.5]
 [6.3 2.7 4.9 1.8]
 [6.  3.  4.8 1.8]
 [6.  2.2 5.  1.5]
 [6.2 2.8 4.8 1.8]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [5.6 2.8 4.9 2. ]
 [5.9 3.  5.1 1.8]
 [4.9 2.5 4.5 1.7]]

Indices of Support Vectors in training data:
[ 16  18  76   7  30  39  44  45  47  58  64  65  90  95   1  15  27  53
  66  72  86  97  98 101]


In [2]:
7. : Write a Python program to:
● Load the Breast Cancer dataset
● Train a Gaussian Naïve Bayes model
● Print its classification report including precision, recall, and F1-score.


from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

# Load Breast Cancer dataset
data = load_breast_cancer()
X, y = data.data, data.target

# Split dataset into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Initialize and train Gaussian Naïve Bayes model
model = GaussianNB()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Print classification report
print("Classification Report for Gaussian Naïve Bayes:\n")
print(classification_report(y_test, y_pred, target_names=data.target_names))

Classification Report for Gaussian Naïve Bayes:

              precision    recall  f1-score   support

   malignant       0.93      0.90      0.92        42
      benign       0.95      0.96      0.95        72

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114



In [3]:
8.: Write a Python program to:
● Train an SVM Classifier on the Wine dataset using GridSearchCV to find the best
C and gamma.
● Print the best hyperparameters and accuracy.


from sklearn.datasets import load_wine
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score

# Load the Wine dataset
wine = load_wine()
X = wine.data
y = wine.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid for C and gamma
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.001, 0.01, 0.1, 1],
    'kernel': ['rbf'] # Using RBF kernel for gamma parameter
}

# Create an SVM classifier
svm = SVC()

# Perform GridSearchCV
grid_search = GridSearchCV(svm, param_grid, cv=5, verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print the best hyperparameters
print(f"Best Hyperparameters: {grid_search.best_params_}")

# Get the best estimator (model with best hyperparameters)
best_svm = grid_search.best_estimator_

# Make predictions on the test set
y_pred = best_svm.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on Test Set: {accuracy:.4f}")


Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best Hyperparameters: {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}
Accuracy on Test Set: 0.8333


In [4]:
9. 9: Write a Python program to:
● Train a Naïve Bayes Classifier on a synthetic text dataset (e.g. using
sklearn.datasets.fetch_20newsgroups).
● Print the model's ROC-AUC score for its predictions.


from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
import numpy as np

# Load dataset (binary classification: e.g. two categories)
categories = ['rec.sport.baseball', 'sci.space']
newsgroups = fetch_20newsgroups(subset='all', categories=categories)

X, y = newsgroups.data, newsgroups.target

# Convert text to TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english')
X_tfidf = vectorizer.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.2, random_state=42, stratify=y
)

# Train Naïve Bayes Classifier
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict probabilities for ROC-AUC
y_proba = model.predict_proba(X_test)[:, 1]

# Compute ROC-AUC score
roc_auc = roc_auc_score(y_test, y_proba)
print(f"ROC-AUC Score: {roc_auc:.4f}")


ROC-AUC Score: 0.9999


In [ ]:
10. : Imagine you’re working as a data scientist for a company that handles email communications.
Your task is to automatically classify emails as Spam or Not Spam. The emails may
contain:
● Text with diverse vocabulary
● Potential class imbalance (far more legitimate emails than spam)
● Some incomplete or missing data
Explain the approach you would take to:
● Preprocess the data (e.g. text vectorization, handling missing data)
● Choose and justify an appropriate model (SVM vs. Naïve Bayes)
● Address class imbalance
● Evaluate the performance of your solution with suitable metrics
And explain the business impact of your solution.




# --> Data Preprocessing:
Text Cleaning:
Lowercase conversion:
         Convert all text to lowercase for consistent comparison.
Remove punctuation:
        Remove unnecessary punctuation like commas, periods, and exclamation marks to focus on the meaningful words.
# Stop word removal:
             Eliminate common words with little meaning (e.g., "the", "a", "and") that might noise up the analysis.
Stemming or Lemmatization:
                   Normalize words to their root form (e.g., "running" and "runs" become "run") to reduce variations and improve feature representation.
# Text Vectorization:
Bag-of-Words (BoW):
             Represent each email as a vector where each element corresponds to a unique word in the vocabulary, with its count indicating how often it appears in the email.
# Term Frequency-Inverse Document Frequency (TF-IDF):
              Weights words based on their frequency within the email and across the entire corpus, giving more importance to rare but relevant words.
N-grams:
            Consider sequences of n words (e.g., bigrams, trigrams) to capture phrases and context.
# Handling Missing Data:
# Imputation
           : Fill missing values with a predefined value (e.g., "unknown" for text fields, mean or median for numerical values).
# Dropping Missing Values:
                    If the percentage of missing values is high in a specific feature, consider dropping that feature or imputing based on other relevant features.


                    # Model Selection (SVM vs. Naïve Bayes):


Naïve Bayes:
Advantages:
                Simple, efficient, performs well with large datasets and sparse features, good for text classification due to its assumption
                  of independence between words (which is not entirely accurate but often works well in practice).
Disadvantages:
      Can be sensitive to highly skewed class distributions.
Support Vector Machines (SVM):
Advantages:
        Effective with non-linear data, good at handling class imbalances, can handle high-dimensional data.
Disadvantages:
        Can be computationally expensive for large datasets, requires careful parameter tuning.
# Addressing Class Imbalance:
Oversampling:
       Randomly duplicate minority class examples to create a more balanced dataset.
# Undersampling:
Randomly remove examples from the majority class.
# Cost-sensitive learning:
Assign higher weights to misclassifications of the minority class during model training.
SMOTE (Synthetic Minority Over-sampling Technique):
Generate synthetic instances of the minority class based on existing data points to address class imbalance.
# Evaluation Metrics:
# Accuracy:
          Overall percentage of correct predictions, but not ideal for imbalanced datasets.
# Precision:
       Proportion of positive predictions that are actually positive (important for minimizing false positives, like sending legitimate emails to spam folder).
# Recall:
        Proportion of positive instances that are correctly classified (important for minimizing false negatives, like missing important emails).
# F1-Score:
      Harmonic mean of precision and recall, provides a balanced measure of performance in imbalanced datasets.

# Busines
# s Impact:
Reduced Spam:
            Implementing a spam filter effectively reduces the number of spam emails users receive, improving inbox usability and user satisfaction.
# Increased Productivity:
           Users spend less time sorting through spam, allowing them to focus on more productive tasks.
# Improved Brand Reputation:
       A reliable spam filter protects users from malicious content, enhancing the company's reputation.

